### ISSUE TITLE
Country rankings highlight the wrong country

### ISSUE THREAD

**Issue by dtreich-itdp** [ITDP/atlas#106]
When viewing country ranking lists in the sidebar, the wrong country is highlighted. In this case, the USA is selected, but South Korea is highlighted in green.

![Screenshot from 2024-05-03 16-16-28](https://github.com/ITDP/atlas/assets/57543011/c04a3d09-4076-448c-a0ee-ca904646ea5f)

**Comment by kauebraga** [comment]
https://github.com/ITDP/atlas/commit/7fa39ea112bc053f5224cf165f8a5da451f191fe should fix

<img width="436" alt="image" src="https://github.com/ITDP/atlas/assets/22420248/9f22e311-e8cb-45c9-849e-cea46e722216">
