### ISSUE TITLE
Disconnected from the server when selecting city after resetting map

### ISSUE THREAD

**Issue by dtreich-itdp** [ITDP/atlas#107]
1) load the Atlas
2) select an indicator and city
3) press 'reset map' 
4) select a new city

This causes a 'disconnected from the server' error for me. The same error appears whether or not I change indicators in between (3) and (4). 

If you don't have time to fix this, it might be best to simply remove the 'reset map' button.

**Comment by kauebraga** [comment]
https://github.com/ITDP/atlas/commit/19a0f25c98156d34281933feb7f456c46a2ce71b should fix it
