### ISSUE TITLE
Placeholder text on display - People Safe from Highways

### ISSUE THREAD

**Issue by mblanco35** [ITDP/atlas#117]
“In NA in 2024, NA% of people lived at least 500km from a grade-separated highway. There were about [highway_km_year]km of highways in this area.” 
<img width="227" alt="image2" src="https://github.com/ITDP/atlas/assets/169686139/a7155113-e5b1-486c-bc13-e40cd0db581b">
<img width="218" alt="image3" src="https://github.com/ITDP/atlas/assets/169686139/9be41f1a-604f-4e67-9a1e-52aff6684549">

**Comment by kauebraga** [comment]
Thank you @mblanco35 , should be fixed on the next deploy.

**Comment by dtreich-itdp** [comment]
@kauebraga  This shows up for me as a big green X

![image](https://github.com/ITDP/atlas/assets/57543011/c42c1fc0-bb15-4cf6-a5fb-764cb813af2c)
