### ISSUE TITLE
“At the level of” Subdivisions lack appropriate coverage

### ISSUE THREAD

**Issue by mblanco35** [ITDP/atlas#118]
Varying subdivisions simply don't cover large swaths of the metropolitan area selected. Here, the entire city of Dhaka is left out, and only the edge of Eastern Honolulu is included. Even if it doesn't change indicators, the feature feels less useful if it doesn't cover the areas of interest. 
<img width="644" alt="image1" src="https://github.com/ITDP/atlas/assets/169686139/6d447d17-c87e-4430-95f4-10d0684f0de5">
<img width="745" alt="image7" src="https://github.com/ITDP/atlas/assets/169686139/69ac6125-15c8-41c7-a575-19cde1f0f242">

**Comment by dtreich-itdp** [comment]
Issue with original OSM data, closing
