### ISSUE TITLE
Left-hand panel drop down can be used to select cities, even if the indicator is unavailable

### ISSUE THREAD

**Issue by dtreich-itdp** [ITDP/atlas#26]
For example, People Near Frequent Transport is unavailable in Havana, so Havana is greyed-out on the world map. But it can still be selected in the left-hand drop-down menu, and if it is, the data for People Near Bikeways is displayed.

**Comment by kauebraga** [comment]
Implemented 
<img width="483" alt="image" src="https://github.com/ITDP/atlas/assets/22420248/b9d93bdf-f420-4e66-9ad3-94d607ee9e38">
