### ISSUE TITLE
Comparison y-axis goes above 100%

### ISSUE THREAD

**Issue by dtreich-itdp** [ITDP/atlas#35]
It's a little confusing to see that the comparison graph can have a y-axis higher than 100%. It makes it seem like even the best cities/districts aren't as good as they could be, and it kind of wastes space on the screen.

![Screenshot from 2023-10-09 15-09-08](https://github.com/ITDP/atlas/assets/57543011/2354f6cd-77b9-4f88-bca2-50304d5a5d7b)

**Comment by kauebraga** [comment]
I have reduced the padding around the max values, so I think it should work!
<img width="652" alt="image" src="https://github.com/ITDP/atlas/assets/22420248/5f6bf764-37ab-4ef9-97ec-b0ae1ba192a6">
