### ISSUE TITLE
Error message "Disconnected from server" and unable to click reload after opening a link 

### ISSUE THREAD

**Issue by kombogo** [ITDP/atlas#37]
After clicking on a source link in the policy recommendation section and going back to the Atlas page, the page shows error message. The reload button and the rest of the page are unclickable. Occurs at random, easier to open links on a new page. 

<img width="954" alt="Screenshot 2023-10-09 163541" src="https://github.com/ITDP/atlas/assets/147443706/0cd8decc-e712-4bee-9e34-ca20d3c4ae6d">

**Comment by kauebraga** [comment]
Thank you, I have redirected those links to open in a new tab :)
