### ISSUE TITLE
Basemap and Legend Overlap After Resetting Map

### ISSUE THREAD

**Issue by Lia-Sanchez-ITDP** [ITDP/atlas#41]
After clicking the reset button the basemap and legend overlap and there is no way to move them without having to reload the page.
<img width="960" alt="Screenshot 2023-10-13 162342" src="https://github.com/ITDP/atlas/assets/147848741/6984a75d-a8d5-4f05-b3e9-a91f44aba768">

**Comment by kauebraga** [comment]
I removed the "elements" list from the world map, that should work to avoid overlapping.
