### ISSUE TITLE
Total population not showing up correctly in left-hand bar

### ISSUE THREAD

**Issue by dtreich-itdp** [ITDP/atlas#49]
It looks like the left-hand bar is displaying the population density numbers twice, instead of showing total pop and weighted density.

![Screenshot from 2023-10-25 15-27-04](https://github.com/ITDP/atlas/assets/57543011/c365557e-84ea-48bd-b30d-9e4947da843b)

**Comment by kauebraga** [comment]
It's fixed for the city-level, will fix for the country
