### ISSUE TITLE
Issues with downloading data

### ISSUE THREAD

**Issue by MaddySL** [ITDP/atlas#56]
1. I can't download any data for all regions at once. I get this error:
![image](https://github.com/ITDP/atlas/assets/55564310/7c198865-bc80-4f38-8d8b-a21c36f0d2c9)

2. When I choose a specific city and try to download the data, it only downloads as a geopackage. Is there a way to get only tabular data in a CSV?
![image](https://github.com/ITDP/atlas/assets/55564310/5c395144-1410-4ee6-8738-a97e2e485ebf)

**Comment by kauebraga** [comment]
On the city level now there is a possibility to download the data either from .csv or .gpkg
<img width="886" alt="image" src="https://github.com/ITDP/atlas/assets/22420248/884bc221-ba8d-4d25-aa9e-e53946ad26c2">

**Comment by MaddySL** [comment]
> On the city level now there is a possibility to download the data either from .csv or .gpkg <img alt="image" width="886" src="https://private-user-images.githubusercontent.com/22420248/281900551-884bc221-ba8d-4d25-aa9e-e53946ad26c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMjMwNTQsIm5iZiI6MTcwMTEyMjc1NCwicGF0aCI6Ii8yMjQyMDI0OC8yODE5MDA1NTEtODg0YmMyMjEtYmE4ZC00ZDI1LWFhOWUtZTUzOTQ2YWQyNmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDIyMDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwNWU1NzY1ZTE0OTM0YzZlMmNhYmQ5NmE3NGMyM2Y1NjU3NTM0YTNhMzg0NzNkZWFjNGFjZDA5NmRhNTMyOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jdDxUh8k8TSKioGkIhRXmOVVYyq3yFmDMOqp7dRCQrE">

@kauebraga Is there a way to download the population density for all of the cities?
