### ISSUE TITLE
No legend

### ISSUE THREAD

**Issue by jorgemichelitdp** [ITDP/atlas#57]
There is no legend for the maps shown at an "agglomeration" level.  Only when you choose "municipalities" or other level the legend appears. Not sure if that is on purpose.

Also, I noticed that Monterrey, Mexico only shows one district when cooshing this level. Might be worth looking into that

**Comment by kauebraga** [comment]
Hi @jorgemichelitdp the legend for the agglomeration levels doesn't exist because there is no color variation at this level (only one value).

@dtreich-itdp to check the Monterrey data
