### ISSUE TITLE
Population density is the same for all years

### ISSUE THREAD

**Issue by MaddySL** [ITDP/atlas#64]
When I go to any city and look at the population density (at any geography level), it's the same for all years- even if I compare 1975 to 2022!

![image](https://github.com/ITDP/atlas/assets/55564310/836d779f-5a64-4d5c-999f-d56fed850843)

![image](https://github.com/ITDP/atlas/assets/55564310/2f2481bd-904e-4b60-8f2b-d1bd4fc2606a)

**Comment by kauebraga** [comment]
Working on this
