### ISSUE TITLE
Selected analysis areas are opaque, which can prevent users from seeing details

### ISSUE THREAD

**Issue by dtreich-itdp** [ITDP/atlas#67]
Once you click on an agglomeration, it turns bright orange, making it impossible to still see the street map/satellite imagery beneath it. This can be annoying for the user.

![Screenshot from 2023-12-06 12-08-40](https://github.com/ITDP/atlas/assets/57543011/ccf5661e-cb57-4182-84a1-54661b7c183c)

Two possible fixes:
-Instead of highlighting the polygon and making it opaque, highlight only the outline (maybe in white), leaving the polygon with the same transparency
-Let the user click outside of any polygon and de-select the current selection

**Comment by kauebraga** [comment]
I have only kept the outline in black - I think it looks good.
<img width="843" alt="image" src="https://github.com/ITDP/atlas/assets/22420248/c8ae8aa8-0b5d-46b9-9e89-795f1855d4b2">

**Comment by dtreich-itdp** [comment]
@kauebraga Does it show up looking nice on 'dark' and 'satellite' basemaps? Maybe a white outline on 'dark'? Reopening for now until you confirm.

**Comment by kauebraga** [comment]
maybe grey works for all of them?

<img width="355" alt="image" src="https://github.com/ITDP/atlas/assets/22420248/d989c755-93a3-4487-8b48-8fc926975398">
<img width="482" alt="image" src="https://github.com/ITDP/atlas/assets/22420248/0642befd-00ee-4b59-9a82-66161eabcc6f">
<img width="405" alt="image" src="https://github.com/ITDP/atlas/assets/22420248/9405c1cd-828b-4627-bd70-d81fd0c440a2">
