### ISSUE TITLE
Internal links to 'about' documentation don't work

### ISSUE THREAD

**Issue by dtreich-itdp** [ITDP/atlas#68]
Links from the left-hand panel to a subsection of the About modal don't function correctly - they open a new tab, which then redirects to the main map.

The ideal behavior would be for the link to open the About modal in the same tab, with the correct section open. But I'm open to other solutions.

I think the only case so far is in the 'people near frequent transport' indicator, but we may add more.

![Screenshot from 2023-12-06 12-16-44](https://github.com/ITDP/atlas/assets/57543011/dc418eaf-4593-450b-a8a9-7dc048af4e69)

**Comment by kauebraga** [comment]
It has been fixed at 5da9b8f312b5e00d9fb3f5e997b7e67dd38284de
