### ISSUE TITLE
Add download options for overlays

### ISSUE THREAD

**Issue by dtreich-itdp** [ITDP/atlas#70]
When viewing an individual urban region and indicator, the user should have an option to download all the overlays for that region and indicator. 

There are two options, both would be okay:
- All these indicators come in the same file (eg., people near protected bikelanes, people near all bikelanes, protected bikelane infrastructure, and all bikelane infrastructure, all in the same zip). 
- The indicators come as separate files, and the user chooses which one(s) to download

**Comment by kauebraga** [comment]
I have added the interface part at https://github.com/ITDP/atlas/commit/5a6079c001a0b95d979828ffb1f576ab99aeba50
It downloads a .zip with all the overlays from the selected indicator/city.
The database also needed to be update, so the changes will only happen when I update the data.
<img width="444" alt="image" src="https://github.com/ITDP/atlas/assets/22420248/8a6babed-e84a-4f09-8666-b361207370c9">
