### ISSUE TITLE
Add scalebar

### ISSUE THREAD

**Issue by dtreich-itdp** [ITDP/atlas#82]
The Atlas view should always have a scalebar, probably located at the bottom right.

**Comment by kauebraga** [comment]
I have removed the legend only in the agglomeration level as raised in the issue #75 . Should the legend be kept? In that admin level there is only one value, so the scale isn't useful.
Is there any other situation you are seeing this?

**Comment by dtreich-itdp** [comment]
Sorry, I should have been more clear! I mean a scalebar marked in kilometers. Something like this should always be visible on any map.

![image](https://github.com/ITDP/atlas/assets/57543011/43087dad-38f3-4b61-ac77-6a13eefe2247)
