### ISSUE TITLE
Possible to include agglomeration names in sub-agglomeration rankings?

### ISSUE THREAD

**Issue by dtreich-itdp** [ITDP/atlas#85]
When viewing sub-agglomeration rankings (for districts, neighborhoods, etc) in many countries, it isn't necessarily clear which district can be found in which agglomeration. For example, in this ranking of 'municipalities' in the USA, I don't know which of these are in which metro areas. And in some cases, there may be more than one municipality of the same name in different agglomerations.

![Screenshot from 2024-01-18 16-38-02](https://github.com/ITDP/atlas/assets/57543011/4ae29aae-78d4-4c59-896a-c6b14c29994c)

If it's possible, I suggest adding the name of the agglomeration after the name of the municipality in this modal. Probably in slightly different font, maybe by bolding the municipality but not the agglomeration, eg

**Everett**, Boston

It's okay if we have to widen the modal to display this.

**Comment by kauebraga** [comment]
suggestion
<img width="478" alt="image" src="https://github.com/ITDP/atlas/assets/22420248/e47772e6-f84e-4d7d-8f3d-d88e60ca3efb">
