### ISSUE TITLE
Possible to switch from continuous to bucketed choropleth legend?

### ISSUE THREAD

**Issue by dtreich-itdp** [ITDP/atlas#89]
The maps might be easier to read if the color-coding on the maps were a set of levels rather than a continuous range. So, right now, the legend is like:
![image](https://github.com/ITDP/atlas/assets/57543011/fdf1cff8-28ab-462d-b4fe-b351e99ff7c5)
But a recent reviewer said it might be easier to read if the colors were sorted into discrete buckets, like:
![image](https://github.com/ITDP/atlas/assets/57543011/457d0e5a-c1d4-4683-a191-ebce0a71bf8d)
(although of course using the same color scheme we already have).

I've discussed this with Aru, who agrees. Is it possible to make this change? Is there any more information you need?

**Comment by kauebraga** [comment]
The closer to it would be using bins. What do you think?
<img width="779" alt="image" src="https://github.com/ITDP/atlas/assets/22420248/602568b6-eea5-4066-a9d8-60d47ee08ead">
