### ISSUE TITLE
Color scaling for Population Density

### ISSUE THREAD

**Issue by dtreich-itdp** [ITDP/atlas#90]
Population Density is a bit of an unusual indicator. For all other indicators, higher values are better and lower ones are worse. But for Population Density, higher values are only better up to a point. After about 20,000 ppl/km2, the benefits of density for walkability start to have diminishing returns, and the risk of overcrowding becomes higher. 

If we're able to implement #89, could we set the highest bucket in Population Density to "20k+ ppl/km2"?

**Comment by kauebraga** [comment]
Implemented 
<img width="989" alt="image" src="https://github.com/ITDP/atlas/assets/22420248/40c55b59-d004-4621-9430-4f8cafc50360">
