### ISSUE TITLE
Variable text does not always update when switching indicators after switching cities 

### ISSUE THREAD

**Issue by dtreich-itdp** [ITDP/atlas#92]
I think this bug is more general, but I'll express it as a single example of what I did that caused it:

1. Open the Atlas
2. Select the Population Density indicator
3. Select Washington DC (by clicking on the map)
4. Use the drop-down to switch the city to Mexico City
5. Use the drop-down to switch the indicator to People Near Protected Bikelanes
6. The variable values in the left-hand panel are incorrect
- The indicator short description is still given as "Mexico City has a weighted population density of 14.3k people per km2"
- The variable values in the main text are wrong: "In Mexico City, X % of residents live within a 300m walk of any bikeway, protected or unprotected. Of those, 1429820 % live within a 300m walk of a physically-protected bikeway. In Mexico City, there are X kilometers of bikeways, of which X are physically-protected." 

![Screenshot from 2024-02-05 15-14-58](https://github.com/ITDP/atlas/assets/57543011/1141871f-f261-4315-a4a6-0c61ffd0290b)

**Comment by kauebraga** [comment]
I couldn't replicate this one! It works fine when I do the same thing you did.
Probably I fixed it before but didn't push the changes?
I will push the modifications e let you know so you can test again.
