### ISSUE TITLE
Tijuana 'compare' feature identifies the wrong city in 'rankings' modal

### ISSUE THREAD

**Issue by dtreich-itdp** [ITDP/atlas#93]
When looking at the Tijuana (/San Diego) agglomeration and using the People Near Bikelanes indicator, Tijuana is incorrectly labeled as being 29th in the USA. However, when the 'rankings' modal is activated, the user sees that Tijuana actually ranks #39, but that Honolulu, the true #29, is highlighted in green.

![Screenshot from 2024-02-11 22-39-03](https://github.com/ITDP/atlas/assets/57543011/abb2e898-1483-4b50-adbd-03da2fe08052)

**Comment by kauebraga** [comment]
That's what I got now. I will push everything and we can check if it stands out!
<img width="1045" alt="image" src="https://github.com/ITDP/atlas/assets/22420248/7b71bd09-dd31-41df-84cd-9527eb7d7671">
